/*
 * generated by Xtext 2.30.0
 */
package zzz.example.mydsl1.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("zzz/example/mydsl1/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
