/*
 * generated by Xtext 2.30.0
 */
package zzz.example.mydsl1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import zzz.example.mydsl1.ui.internal.Mydsl1Activator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mydsl1Activator.getInstance().getInjector("zzz.example.mydsl1.MyDsl");
	}

}
