/*
 * generated by Xtext 2.30.0
 */
package zzz.example.mydsl1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import zzz.example.mydsl1.ui.internal.Mydsl1Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Mydsl1Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Mydsl1Activator activator = Mydsl1Activator.getInstance();
		return activator != null ? activator.getInjector(Mydsl1Activator.ZZZ_EXAMPLE_MYDSL1_MYDSL) : null;
	}

}
